Modifications for Digital Input Multiplexers
MobiFlight/MobiFlight-FirmwareSource pull request #169
Opened 2022-04-01 20:41 UTC by DocMoebiuz

fixes #119

2022-04-02 11:18 UTC, GioCC commented on _Boards/Atmel/Board_Uno/MFBoards.h
> +#define MAX_INPUT_SHIFTERS  2
MAX_INPUT_SHIFTERS is repeated

2022-04-02 11:21 UTC, GioCC requested changes
Only thing I noticed is a repeated line in [_Boards/Atmel/Board_Uno/MFBoards.h](https://github.com/MobiFlight/MobiFlight-FirmwareSource/pull/169/files#diff-5caba37e39e6c44acb1bbd76bf5e9755b94ece0a9ad28388576181a39e8a8ee9)

2022-04-02 11:27 UTC, GioCC commented on src/Config.cpp
> +// reads the EEPRROM until NULL termination and returns the number of characters incl. NULL termination, starting from given address
Not really worth mentioning, but "EEPRROM" is spelled wrong, and the "\0" char is a NUL char used as terminator; NULL is something that has "no" value (or the "placeholder" value representing that).

2022-04-02 14:48 UTC, GioCC approved these changes

2022-04-04 10:19 UTC, GioCC approved these changes

2022-04-04 16:02 UTC, GioCC approved these changes

2022-04-04 16:35 UTC, MobiFlight-Admin approved these changes
Thanks!

2022-04-04 16:47 UTC, merged