Read config from eeprom only if no config is in Flash
MobiFlight/MobiFlight-FirmwareSource pull request #327
Opened 2024-07-06 07:15 UTC by elral

## Description of changes

If a configuration is already saved in the EEPROM, and the board gets updated with a new Firmware where the configuration is part of the flash, the exsiting configuration in the EEPROM gets ignored and only the one from the flash gets reported to the connector and loaded into the internal memory.

Before sending the configuration to the connector, it gets's checked if a configuration is stored in the flash. If this is the case (configLength > 0), this configuration is send to the connector. If no config in the flash is available (configLength = 0) but a config in the EEPROM saved, this config gets send to the connector.
The same applies for loading the config into the internal memory.

For now it is only checked if a configuration in the EEPROM `OR` Flash is available. If a configuration is saved, this one gets reported to the connector and loaded into the internal memory.

Fixes #326

2024-07-08 06:57 UTC, elral commented
For backward compatibility it is first checked, if a config in EEPROM is available. If so, this config will still be used.
Otherwise it is checked, if a config in Flash is available and if so this config get's used.

It is still possible, to upload a user config even if a config in flash is available. This overrules the flash config.
But this enables also the user, to use the flash config if an empty config get's uploaded.
The only drawback is that the connector has to be restarted if an empty config is uploaded and the flash config get's be used because the config is not read again after an upload.

2024-09-04 20:21 UTC, DocMoebiuz requested changes

2024-09-04 20:21 UTC, DocMoebiuz commented on src/Config.cpp
> +    // A config can be in flash or in EEPROM, bur only one must be used
```suggestion
    // A config can be in flash or in EEPROM, but only one option must be used
```

2024-09-04 20:21 UTC, DocMoebiuz commented on src/Config.cpp
> +    if (configLengthEEPROM + cfgLen + 1 < MEM_LEN_CONFIG) {
```suggestion
   bool maxConfigLengthNotExceeded = configLengthEEPROM + cfgLen + 1 < MEM_LEN_CONFIG;
    if (maxConfigLengthNotExceeded) {
```

2024-09-04 20:21 UTC, DocMoebiuz commented on src/Config.cpp
>  }
I would like to avoid so many if-else blocks
Suggestion:

``` cpp
void readConfig()
{
    uint8_t numberDevices[kTypeMax] = {0};

    bool useFlash = configLengthFlash > 0;
    bool useEEPROM = configLengthEEPROM > 0;

    // Early return if no valid configuration is found
    if (!useFlash && !useEEPROM) {
        InitArrays(numberDevices);
        return;
    }

    // Determine which configuration to use and proceed
    GetArraySizes(numberDevices, useFlash);
    InitArrays(numberDevices);
    readConfigFromMemory(useFlash);
}
```

2024-09-04 20:21 UTC, DocMoebiuz commented on src/Config.cpp
> +    } else if (configLengthFlash > 0) {
since now i am seeing this over and over again, what about extracting this into a method: 

``` cpp
bool configStoredInFlash() {
  configLengthFlash > 0
}
```

Would improve readability in my opinion.

2024-09-05 07:00 UTC, DocMoebiuz approved these changes

2024-09-05 07:01 UTC, merged

2024-09-08 05:52 UTC, elral commented on src/Config.cpp
>  }
Ups, `InitArrays(numberDevices);` is not required for the early return. But as the number of all devices is set to `0`, nothing worse happens.