write eeprom or name if they are available even config is in flash
MobiFlight/MobiFlight-FirmwareSource pull request #333
Opened 2024-09-05 08:22 UTC by elral

## Description of changes

In addition to PR #327 fully backwards compatibility is now ensured.
Once a config is in EEPROM, this config can still be changed even a config is in flash.
Once a name is in EEPROM, this name can still be changed even a config is in flash.
If no name and no config is in EEPROM, name and config can not be changed anymore.

2024-09-16 15:38 UTC, DocMoebiuz requested changes
only small notes and a question which use case that is where it can be 

`if (configStoredInEEPROM() || !configStoredInFlash())`

2024-09-16 15:38 UTC, DocMoebiuz commented on src/Config.cpp
> +        // MFeeprom.commit() is not required, name is always set before config
better remove unnecessary lines

2024-09-16 15:38 UTC, DocMoebiuz commented on src/Config.cpp
> +    if (configStoredInEEPROM() || !configStoredInFlash()) {
is this case not the case when !configStoredInFlash()?

2024-09-16 15:38 UTC, DocMoebiuz commented on src/Config.cpp
> +    if (configStoredInEEPROM() || !configStoredInFlash()) {
is this case not the case when !configStoredInFlash()?

2024-09-16 15:38 UTC, DocMoebiuz commented on src/Config.cpp
> +            // staus message to connector, failure on setting config
With these multilines in the else block better use `{` `}`

2024-09-17 04:24 UTC, elral commented on src/Config.cpp
> +        // MFeeprom.commit() is not required, name is always set before config
I see this more as an important comment for two reasons:
* users which are not familiary with the code may ask why the name gets not commited to the EEPROM
* should the connector differ between saving the config the name (I don't see a reason to save always the name even it is unchanged) in the future, commiting has to be done. This comment is to remember (hopefully) this.

2024-09-17 04:35 UTC, elral commented on src/Config.cpp
> +            cmdMessenger.sendCmd(kStatus, -1);
For now the connector reports a successfull upload of the config, even if `-1` is send back.
If no message is send back, the connector shows an error message (due to time out) that the config uploads fails.

Does it make sense to uncomment `cmdMessenger.sendCmd(kStatus, -1);` as long as the connector does not handle this?
There were discussion before to implement a `kError` message which would be sensefull also in this case ;)

2024-09-30 20:35 UTC, DocMoebiuz approved these changes

2024-09-30 20:37 UTC, merged